[functions]
  # Directory for serverless functions
  directory = "netlify/functions/"
  # Scheduled function to log IP daily
  [functions."log-ip-daily"]
    schedule = "@daily"

[build]
  publish = "dist" # Or wherever your built frontend assets are
  functions = "netlify/functions" # This tells Netlify where your functions are located

# If you have specific build commands
# command = "npm run build"