
[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild" # Use esbuild for faster and more reliable bundling.
  external_node_modules = [
    "@netlify/neon", 
    "undici",      
    "jsonwebtoken" 
  ]
